Render Markdown with commonmarker
codebar/planner pull request #1423
Opened 2020-11-07 17:35 UTC by gnclmorais

### Review https://github.com/codebar/planner/pull/1419  first

As suggested by @despo, I took a stab at replacing `redcarpet` gem with [`commonmarker`](https://github.com/gjtorikian/commonmarker) to see how troublesome would be, and… end up being pretty simple! After #1419 being merged into `master`, I’ll rebase this PR and it will be ready for review. 😄

2020-11-07 19:02 UTC, despo requested changes
Looks good but why not just call `dot_markdown()` instead of `raw(CommonMarket.html())` from the guide as well then? Not sure I'm missing something here?

2020-11-07 19:02 UTC, despo commented on app/views/admin/portal/guide.html.haml
> +      = raw CommonMarker.render_html("`Member.find(:id).add_role(:organiser, Chapter.find(:id))`")
can we not just use `dot_markdown(text)` in the entire guide as well? Then we would have only one place referencing common marker.

2020-11-07 19:09 UTC, despo commented
@gnclmorais Thanks for your PR, it looks great. I have left some minor feedback.

As for not using `html_safe` or `raw` I'm not sure how we could do this. I understand that it can be classed as not safe, however the places that we allow for this to be called either provide static content, eg the guide, or the content is provided by authorised users e.g. organisers or admin of the app, which we trust.

We can however configure `commonmarker` to use the tagfilter extension which should filter unsafe tags like <script> 

This can be done by updating the call to common marker to be something like this:

`CommonMarker.render_html(text, :DEFAUT, %i[tagfilter]).html_safe).html_safe`

2020-11-09 22:02 UTC, gnclmorais commented
Hey @despo! I took a look at your (great!) suggestion and it seems that `CommonMarker.render_html(text, :DEFAUT)` is enough to turn…
```html
<scrip>alert("Hi");</script>
```
… into this…
```html
<p><!-- raw HTML omitted -->alert(&quot;Hi&quot;);<!-- raw HTML omitted --></p>
```
… making `%i[tagfilter]` irrelevant. Seems like the default rendered is already safe enough.

2020-11-09 22:07 UTC, despo commented
@gnclmorais sounds good to me!

2020-11-10 21:27 UTC, despo approved these changes
LGTM 💯

2020-11-10 21:27 UTC, merged